data_path: ./data/tushare/
tushare_token: xxxxxxxxxx
db_config:
  host: localhost
  port: 3306
  user: root
  password: xxxxxxxxxx
  database: stock
data_config:
  code_prefixes:
    - '600'
    - '601'
    - '603'
    - '000'
    - '001'
    - '002'
  batch_size: 100_0000
