data_path: ./data/tushare/
tushare_token: xxxxxxxxxx
db_config:
  host: localhost
  port: 3306
  user: root
  password: xxxxxxxxxx
  database: stock
data_config:
  code_prefixes:
    - '60'
    - '00'
  batch_size: 100_0000
